const styles = {
  sidebar: {
    width: "18vw",
    flex: "0 0 18vw" as const,
    flexShrink: 0,
    position: "sticky" as const,
    top: 0,
    left: 0,
    height: "100vh",
    background: "#fafafa",
    border: "1px solid #eee",
    padding: "10px",
    margin: 0,
    display: "flex" as const,
    flexDirection: "column" as const,
    justifyContent: "space-between" as const,
    fontFamily: "'DM Sans', sans-serif",
    boxSizing: "border-box" as const,
  },
  header: {
    background: "#fafafa",
    padding: "12px",
    borderBottom: "1px solid #f2f2f2",
    fontWeight: 800,
    fontSize: 16,
    color: "#1a1a1a",
    display: "flex" as const,
    alignItems: "center" as const,
    gap: 8,
  },
  nav: {
    flex: 1,
    overflowY: "auto" as const,
    padding: "6px",
    display: "flex" as const,
    flexDirection: "column" as const,
    gap: 2,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: 500,
    color: "#aaa",
    padding: "4px 10px",
    marginTop: 12,
    marginBottom: 2,
    textTransform: "uppercase",
    letterSpacing: "0.05em",
  },
  link: (active: boolean) => ({
    display: "flex" as const,
    alignItems: "center" as const,
    gap: 10,
    padding: "9px 12px",
    borderRadius: 10,
    cursor: "pointer" as const,
    fontSize: 14,
    fontWeight: active ? 600 : 400,
    color: active ? "#1a1a1a" : "#808080",
    background: active ? "#ebebeb" : "transparent",
    textDecoration: "none" as const,
    transition: "background 140ms ease, color 140ms ease",
    userSelect: "none" as const,
  }),
  icon: {
    width: 26,
    height: 26,
    borderRadius: 8,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 16,
  },
  badge: {
    marginLeft: "auto",
    fontSize: 11,
    fontWeight: 700,
    padding: "2px 7px",
    borderRadius: 9999,
    background: "#EAF9E3",
    color: "#2B8E1C",
  },
  footer: {
    borderTop: "1px solid #f2f2f2",
    padding: "10px 12px",
    display: "flex",
    alignItems: "center",
    gap: 10,
  },
  avatar: {
    width: 32,
    height: 32,
    borderRadius: "50%",
    background: "#e0e0e0",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 13,
    fontWeight: 700,
    color: "#555",
    flexShrink: 0,
  },
};

export default styles;